### ISSUE TITLE
A suggestion : AWS S3 + Cloudfront

### ISSUE THREAD

**Issue by saurabh0719** [rishi255/cdn#1]
#### Description :  

AWS S3 + Cloudfront is an easy to set up delivery network with a lot of granular control (for http headers, cache control etc.). [Refer here](https://medium.com/tensult/creating-aws-cloudfront-distribution-with-s3-origin-ee47b8122727). Personally feel its very flexible. 

Just an alternative, Cloudflare has its own benefits surely.

**Comment by rishi255** [comment]
Thanks! This seems promising and I'll definitely look into it soon.
